branches:
  only:
  - master

services:
- docker

env:
  global:
  - DOCKER_IMAGE_APACHE_LIVE=peregrinecms/apache-live
  - DOCKER_IMAGE_APACHE_STAGE=peregrinecms/apache-stage
  - DOCKER_USERNAME=gastongonzalez
  matrix:
  - secure: x21cQdxtCEHV9BrGPmP+FzaraSoRbTAty2DDeNbycAjcJZsJt4hMcUy5tOBShCY2o/IlF6jVDHmDo3inRPbPQvhop9b4iK3vSfnzfk1cT+K2/TJw9r0ZtWS55A2nkxkG6QidJE03Oc557MY1ouJX5JTSoAm2FO5AQ+AOXorxtwSpBCGQTHGNOmRhV6CayerReaqoG8zEiVLin/uRf/vv0IqyW86vSe5mQWCRIK0V4Rjm1E8so9y/yjTxDU4KazTN6+Yu37m70pV3J42OcNr1nfF7tMjqu9RLUtxArDzmGPMKuAXYisq6tARkcB5MRZ1xVT0u25IFEKLyBYySbjMeD/fF3gra4yCnijnqGraYeXQ2IdPxf/5kcrtt85OMRG4OV3KDCrCOt64yX0t254UWccD1xN5nWm8ht61gAcpvZ8/yy/bD1MKeJvWBCpMYG5MblO33da78sMO0yY8ziSO0wO7fLx0b/0wspfz7dSlXo8FKKgj/+xKUnmi0ZWnhxwvi5fhvJIBANwmdE5Tmcy+OtgbhRoMfNHIQv3Bwqdolpp9Z8ROQxGnpUd4W4qUGz1UoO49DCwAEUz/j7E4zZKJyG4U+ZyHcFotN1KTCXkxR5O/d2Nej1jAL0fQWzuk2pAGsBkQAAbvcHtJIkmK5hCxXm3wVK9S/Cii68zfIb8QUudI=

before_script:
- branch="$(echo ${TRAVIS_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]')"

script:
- cd live && ./build.sh && cd ../stage && ./build.sh

after_script:
- docker images

before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$DOCKER_IMAGE_APACHE_LIVE" "${DOCKER_IMAGE_APACHE_LIVE}:latest"
- docker tag "$DOCKER_IMAGE_APACHE_STAGE" "${DOCKER_IMAGE_APACHE_STAGE}:latest"

deploy:
  provider: script
  script: docker push ${DOCKER_IMAGE_APACHE_LIVE}:latest && docker push ${DOCKER_IMAGE_APACHE_STAGE}:latest
  on:
    branch: master
