branches:
  only:
  - master
services:
- docker
env:
  global:
  - DOCKER_IMAGE_APACHE_LIVE=peregrinecms/apache-live
  - DOCKER_IMAGE_APACHE_STAGE=peregrinecms/apache-stage
  - DOCKER_USERNAME=gastongonzalez
  matrix:
  - secure: oQgFaxbgIuv9IhEOgz84Jiya7kiuK+h15qW0qCv6cEs7gdD249vzz9MtaY4g8K7cHiur5U2WnwRFafCRlY+ifbi1Z6uysYD6xjiPTy5mdLPVnA8U+vMaN+bjHloprqkqt45rVr+tK0Ii5b7DvaQSHJ5QimTs6OwvilNr9T/rUGLbBw1Ukfs2YhhTzdkajdXi2osCbGxpRDw65gjsq/FRXKtPVRNJ9bZUBmpr7mb48wGssTQgXkZ+s8zCQ7O8dVFMMwcPQJUihR7n/7y1WfMf9V5UsdVuVoGzNYc5lp/alSw5L4DWwsBqLcDOAOQTpCFT5t+xOPh7dsuunDWXHLvPhs4JooH6Qrly5S8CB6xVsK4tHzPWCpDXKQilaLY/yIEohhadepCzyZ10vfA9feKaT7HTDqGSULw42I2ksaRkOp3l9YrLCAumXQm7fyV6Mro/uDm3QuK81wkoJC3OUuWaoR0UXE2L75KKPcT5aARlDGHQ2Nifg9NjmULBNkGGKpRhZDMejSr9urDb9GUDEoULNWMpEPw3BjiIO5nJdIxi14FIrGHVydXphNULb2wNcYZgruf9jyOc9UtG4wAXdNBxK/9eaHypibo2Yb9FMPRrAFaw+RY8dmaDSxl85uELVZtXe+6EC1UxZHDMAA6z1+vHEfW/sLBG+JY59e/pCzQKGjE=
  - secure: qK4RC7Jc6jEXbKZdPjfcsKXjwlFcQQ2OSEVsNHxkOJK4q1BqXjCTtbnsJF+I778HxSR8TXbodNY6xZoGTNCt5F/8hLDdhWQerZ4gFXTHRvkiSuZhtqpShiyfuzhcjMRyjihl5qcFDvkQFEapE1OfMyjDWINLZDLJhECWG7yA7O9wNwPLvRxReXkfZF0eORnWgH7hm0NpKAT7MrIS5cIap2dZfbDaii5Bz7XN0BNYD0lsft4OLiBza+tnJ6h8zHJ6dVUODXvfHVr8TZuI5e+6R3I1ddfkp2JQ3hLPfVbdKKk6SownNab5pmYakOXZKH6mpbK3TkWlgRRLDH6lcyTiky2aRLI2bWSMMlgwaJmfWOK/PglTlJICm23n39izs6dC2KpDThys107lQYYDAiGfN6lCYIl4fkBsR7+kCPYdDo3WDQS4MbWiis5JeCXwvlUKTa3DCC3CNf5P/LvUMOsccB6imdX2K40dgeKZUvR7kTylob2z5HbkHj6HVW9z71diWZCEAvSA375NTFxp8SCqL9CrCO3rddBKeoGqJAHOxo52afXqFVdgfexInW9rKPEmYzYMhhL+8Ckl7hZ5mIo+CYtHLFHwrMeMwk8/hwS7Neg6C7oK1rnUsgiT0+F7vXh1FbsBUyHognwz3rFhaQEK6q3NEtr9vsktgtlYIFq+z2o=
before_script:
- branch="$(echo ${TRAVIS_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]')"
script:
- cd live && ./build.sh && cd ../stage && ./build.sh
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$DOCKER_IMAGE_APACHE_LIVE" "${DOCKER_IMAGE_APACHE_LIVE}:latest"
- docker tag "$DOCKER_IMAGE_APACHE_STAGE" "${DOCKER_IMAGE_APACHE_STAGE}:latest"
deploy:
  provider: script
  script: docker push ${DOCKER_IMAGE_APACHE_LIVE}:latest && docker push ${DOCKER_IMAGE_APACHE_STAGE}:latest
  on:
    branch: master
